# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Unique assistant ID
assistant_id: 20250527-221545-dark-headline

# NLU language
language: en

# NLU Pipeline
pipeline:
  - name: WhitespaceTokenizer

  # Use RegexFeaturizer to support lookup tables and regex patterns
  - name: RegexFeaturizer

  # Use RegexEntityExtractor with lookup tables enabled
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True

  # Lexical and syntactic features
  - name: LexicalSyntacticFeaturizer

  # Word-level count vectors
  - name: CountVectorsFeaturizer
    analyzer: word
    lowercase: true

  # Character-level count vectors (n-grams)
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # DIETClassifier handles both intent classification and entity recognition
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
    entity_recognition: true

  # Maps synonyms like "pro shampoo" to "shampoo pro"
  - name: EntitySynonymMapper

  # Handles retrieval-based responses (e.g., FAQs)
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  # Fallback for low-confidence predictions
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Dialogue Policies
policies:
  - name: MemoizationPolicy

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true

  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
